//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakasryhmät
    {
        public int AsiakasryhmäId { get; set; }
        public int AsiakasId { get; set; }
        public int RyhmäId { get; set; }
    
        public virtual Asiakasryhmäluokat Asiakasryhmäluokat { get; set; }
        public virtual Asiakkaat Asiakkaat { get; set; }
    }
}
