//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektitDBCareEntities : DbContext
    {
        public ProjektitDBCareEntities()
            : base("name=ProjektitDBCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiakaskategorialuokat> Asiakaskategorialuokat { get; set; }
        public virtual DbSet<Asiakasryhmäluokat> Asiakasryhmäluokat { get; set; }
        public virtual DbSet<Asiakasryhmät> Asiakasryhmät { get; set; }
        public virtual DbSet<Asiakkaat> Asiakkaat { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Postitoimipaikat> Postitoimipaikat { get; set; }
        public virtual DbSet<Sähköposti> Sähköposti { get; set; }
        public virtual DbSet<Tapahtumalajit> Tapahtumalajit { get; set; }
        public virtual DbSet<Tapahtumat> Tapahtumat { get; set; }
        public virtual DbSet<Vakioaiheet> Vakioaiheet { get; set; }
    }
}
