//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sähköposti
    {
        public int SähköpostiId { get; set; }
        public string Vastaanottaja { get; set; }
        public Nullable<System.DateTime> LähetysPvm { get; set; }
        public Nullable<System.DateTime> LähetysKlo { get; set; }
        public Nullable<int> AiheId { get; set; }
        public string Otsikko { get; set; }
        public string Viesti { get; set; }
    
        public virtual Vakioaiheet Vakioaiheet { get; set; }
    }
}
