//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tapahtumalajit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tapahtumalajit()
        {
            this.Tapahtumat = new HashSet<Tapahtumat>();
        }
    
        public int TapahtumalajiId { get; set; }
        public string TapahtumalajiNimi { get; set; }
        public string TapahtumalajiKuvaus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tapahtumat> Tapahtumat { get; set; }
    }
}
