//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vakioaiheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vakioaiheet()
        {
            this.Sähköposti = new HashSet<Sähköposti>();
        }
    
        public int AiheId { get; set; }
        public string AiheenNimi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sähköposti> Sähköposti { get; set; }
    }
}
